#!/bin/bash

function harmony_function() {
    function join_by {
        local IFS="$1";
        shift;
        echo "$*";
    }

    function make_uuid() {
        uuid=$(uuidgen)
        echo "$uuid"
    }

    function make_path_to_files() {
        FILES_IN_CONTAINER=()
        for f in "$@"; do
            FULL_PATH=$(join_by "/" ".." "code" "$f")
            FILES_IN_CONTAINER+=("\"$FULL_PATH\"")
        done
        echo "${FILES_IN_CONTAINER[@]}"
    }

    function make_run_cmd() {
        ARGS=("docker" "run")
        if [ -n "$1" ]; then
            ARGS+=("-m")
            ARGS+=("$1M")
            ARGS+=("--memory-swap")
            ARGS+=("$1M")
        fi
        ARGS+=("--name")
        ARGS+=("$2")

        ARGS+=("-v")
        PWD=$(pwd)
        ARGS+=("$PWD:/code")
        ARGS+=("-w" "/harmony")
        ARGS+=("-i")
        ARGS+=("-t" "anthonyyang/harmony-docker")

        shift; shift;
        ARGS+=("./wrapper.sh")
        ARGS+=("$@")

        CMD=$(join_by " " "${ARGS[@]}")
        echo "$CMD"
    }

    function make_clean_cmd() {
        echo "docker container rm $1"
    }

    function make_get_json_cmd() {
        CWD=$(pwd)
        echo "docker cp $1:/harmony/charm.json $CWD/charm.json"
    }

    function make_get_html_cmd() {
        CWD=$(pwd)
        echo "docker cp $1:/harmony/harmony.html $CWD/harmony.html"
    }

    function make_kill_cmd() {
        echo "docker container kill $1"
    }

    function main() {
        MAX_MEMORY="$1"
        shift;
        name=$(make_uuid)
        run_cmd=$(make_run_cmd "$MAX_MEMORY" "$name" "$@")
        get_json_cmd=$(make_get_json_cmd "$name")
        get_html_cmd=$(make_get_html_cmd "$name")
        kill_cmd=$(make_kill_cmd "$name")
        clean_cmd=$(make_clean_cmd "$name")

        if eval "$run_cmd"; then
            eval "$get_json_cmd"
            eval "$get_html_cmd"
        else
            echo "Killed"
            eval "$kill_cmd" &>/dev/null
        fi
        eval "$clean_cmd" &>/dev/null
    }

    function setup() {
        OPTIONS=()
        FILENAMES=()
        while [[ $# -gt 0 ]]; do
            key="$1"
            case $key in
                --memory)
                MAX_MEMORY="$2"
                shift # past argument
                shift # past value
                ;;
                -a|-A|-j|-f|-h|--help|-b|-d|-s|-t|-v|--version)
                OPTIONS+=("$key")
                shift
                ;;
                --const|-c|-m|--module)
                OPTIONS+=("$key" "$2")
                shift # past argument
                shift # past value
                ;;
                *)    # unknown option
                FILENAMES+=("$1") # save it in an array for later
                shift # past argument
                ;;
            esac
        done
        FULL_FILE_PATHS=$(make_path_to_files "${FILENAMES[@]}")
        POSITIONALS="${OPTIONS[*]} ${FULL_FILE_PATHS[*]}"
        main "$MAX_MEMORY" "${POSITIONALS[@]}"
    }
    setup "$@"
}

harmony_function "$@"
