#!/bin/bash

function harmony_function() {
    function join_by {
        local IFS="$1";
        shift;
        echo "$*";
    }

    function make_id() {
        ID=()
        LETTERS=(1 2 3 4 5 6 7 8 9 0 a b c d e f g)
        for _ in $(seq 1 32); do
            INDEX=$((RANDOM % 16))
            ID+=("${LETTERS[INDEX]}")
        done
        idNumber=$(join_by '' "${ID[@]}")
        echo "$idNumber"
    }

    function make_path_to_files() {
        FILES_IN_CONTAINER=()
        for f in "$@"; do
            FULL_PATH=$(join_by "/" ".." "code" "$f")
            FILES_IN_CONTAINER+=("'$FULL_PATH'")
        done
        echo "${FILES_IN_CONTAINER[@]}"
    }

    function make_run_cmd() {
        ARGS=("docker" "run")
        if [ -n "$1" ]; then
            ARGS+=("-m")
            ARGS+=("$1M")
            ARGS+=("--memory-swap")
            ARGS+=("$1M")
        fi
        ARGS+=("--name")
        ARGS+=("$2")

        ARGS+=("-v")
        PWD=$(pwd)
        ARGS+=("$PWD:/code")
        ARGS+=("-w" "/harmony")
        ARGS+=("-i")
        ARGS+=("-t" "anthonyyang/harmony-docker")

        shift; shift;
        ARGS+=("./wrapper.sh")
        ARGS+=("$@")

        CMD=$(join_by " " "${ARGS[@]}")
        echo "$CMD"
    }

    function make_clean_cmd() {
        echo "docker container rm $1"
    }

    function make_get_json_cmd() {
        CWD=$(pwd)
        echo "docker cp $1:/harmony/charm.json $CWD/charm.json"
    }

    function make_get_html_cmd() {
        CWD=$(pwd)
        echo "docker cp $1:/harmony/harmony.html $CWD/harmony.html"
    }

    function make_kill_cmd() {
        echo "docker container kill $1"
    }

    function main() {
        MAX_MEMORY="$1"
        MAX_TIMEOUT="$2"
        shift; shift;
        name=$(make_id)
        run_cmd=$(make_run_cmd "$MAX_MEMORY" "$name" "$@")
        get_json_cmd=$(make_get_json_cmd "$name")
        get_html_cmd=$(make_get_html_cmd "$name")
        kill_cmd=$(make_kill_cmd "$name")
        clean_cmd=$(make_clean_cmd "$name")

        function timeout() {
            time=$1
            # start the command in a subshell to avoid problem with pipes
            # (spawn accepts one command)
            command="/bin/sh -c \"$2\""
            expect -c "set echo \"-noecho\"; set timeout $time; spawn -noecho $command; expect timeout { exit 1 } eof { exit 0 }"
            if [ $? = 1 ] ; then
                echo "Timeout after ${time} seconds"
            fi
        }
        if [ -n "$MAX_TIMEOUT" ]; then
            timeout "$MAX_TIMEOUT" "$run_cmd"
        else
            eval "$run_cmd"
        fi
        eval "$get_json_cmd"&>/dev/null
        eval "$get_html_cmd"&>/dev/null
        eval "$kill_cmd" &>/dev/null
        eval "$clean_cmd" &>/dev/null
    }

    function setup() {
        OPTIONS=()
        FILENAMES=()
        while [[ $# -gt 0 ]]; do
            key="$1"
            case $key in
                --memory)
                MAX_MEMORY="$2"
                shift # past argument
                shift # past value
                ;;
                --timeout)
                MAX_TIMEOUT="$2"
                shift # past argument
                shift # past value
                ;;
                -a|-A|-j|-f|-h|--help|-b|-d|-s|-t|-v|--version)
                OPTIONS+=("$key")
                shift
                ;;
                --const|-c|-m|--module)
                OPTIONS+=("$key" "$2")
                shift # past argument
                shift # past value
                ;;
                *)    # unknown option
                FILENAMES+=("$1") # save it in an array for later
                shift # past argument
                ;;
            esac
        done
        FULL_FILE_PATHS=$(make_path_to_files "${FILENAMES[@]}")
        POSITIONALS="${OPTIONS[*]} ${FULL_FILE_PATHS[*]}"
        main "$MAX_MEMORY" "$MAX_TIMEOUT" "${POSITIONALS[@]}"
    }
    setup "$@"
}

harmony_function "$@"